version: 2.1

jobs:
  build-mac-dev:
    macos:
      xcode: 13.4.0
#      resource_class: macos.x86.medium.gen2

    working_directory: $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager

    steps:
      - run: sudo systemsetup -settimezone Asia/Tokyo
      - checkout

#---------------------------------------------------
# 証明書の登録
#---------------------------------------------------
      # - run:
      #     name: "fastlane match"
      #     command: |

#---------------------------------------------------
# ビルド
#---------------------------------------------------
      - run:
          name: "Build"
          command: |
            cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
            sudo bash ./build.sh

workflows:
  version: 2.1
  mdm-cicd-workflow:
    jobs:
      - build-mac-dev
