# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-mac-dev:
    macos:
      xcode: 13.4.0

    working_directory: $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager

    steps:
      - run: sudo systemsetup -settimezone Asia/Tokyo
      - checkout

      - run: echo "Only build pull requests OFF"

workflows:
  version: 2.1
  mdm-cicd-workflow:
    jobs:
      - build-mac-dev:
          filters:
            branches:
              only: develop
