version: 2.1

jobs:
  build-mac-dev:
    macos:
      xcode: 13.4.0
#      resource_class: macos.x86.medium.gen2

    working_directory: $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager

    steps:
      - run: sudo systemsetup -settimezone Asia/Tokyo
      - checkout

#---------------------------------------------------
# fastlane update.
#---------------------------------------------------
      - run:
          name: "fastlane update"
          command: |
            export GOPATH=$HOME/go
            cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
            bundle update --bundler
            bundle install
            bundle update fastlane

#---------------------------------------------------
# 証明書の登録
#---------------------------------------------------
      # - run:
      #     name: "fastlane match"
      #     command: |
      #       cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
      #       fastlane run opt_out_usage
      #       fastlane match development --readonly
      - run:
          name: "fastlane import"
          command: |
            cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
            fastlane run opt_out_usage
            fastlane import
#            fastlane import --skip_certificate_matching true

#---------------------------------------------------
# ビルド
#---------------------------------------------------
      - run:
          name: "Build"
          command: |
            cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
            sudo bash ./build.sh

workflows:
  version: 2.1
  fastlane-test_workflow:
    jobs:
      - build-mac-dev
