# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-mac-dev:
    macos:
      xcode: 13.4.0
#      resource_class: macos.x86.medium.gen2

    working_directory: $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager

    steps:
       # TimeZoneを設定する
      - run: sudo systemsetup -settimezone Asia/Tokyo
      - checkout

#---------------------------------------------------
# 証明書の登録
#---------------------------------------------------
      - run:
          name: "security import(login)"
          command: |
            sudo security import ~/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager/certs/development/Developer\ ID\ Application.p12 -k ~/Library/Keychains/login.keychain-db -P Kaihatsu1924 -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
            sudo security find-identity -v -p codesigning
#            sudo security list-keychains

#       - run:
#           name: "security import(morisawa)"
#           command: |
#             sudo security create-keychain -p Kaihatsu1924 ~/Library/Keychains/morisawa.keychain-db
#             sudo security list-keychains -d user -s ~/Library/Keychains/morisawa.keychain-db
#             sudo security import ~/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager/certs/development/Developer\ ID\ Application.p12 -k ~/Library/Keychains/morisawa.keychain-db -P Kaihatsu1924 -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
# #            sudo security default-keychain -d user -s ~/Library/Keychains/morisawa.keychain-db

#---------------------------------------------------
# ビルド
#---------------------------------------------------
      - run:
          name: "Build"
          command: |
            cd $HOME/go/src/github.com/morisawa-tokyo-dev/morisawa-desktop-manager
            sudo bash ./build.sh

#========================================================
#　ワークフローの定義
#========================================================
workflows:
  version: 2.1
  mdm-cicd-workflow:
    jobs:
      - build-mac-dev
